	.align 2
voicegroup203:: @ Alto Sax Samples
	voice_directsound 60, 0, DirectSoundWaveData_alto_sax_55, 248, 240, 247, 165  @ 0 G2
	voice_directsound 60, 0, DirectSoundWaveData_alto_sax_59, 248, 241, 248, 166  @ 1 B2
	voice_directsound 60, 0, DirectSoundWaveData_alto_sax_62, 248, 242, 249, 167  @ 2 D3
	voice_directsound 60, 0, DirectSoundWaveData_alto_sax_65, 248, 243, 250, 168  @ 3 F3
	voice_directsound 60, 0, DirectSoundWaveData_alto_sax_69, 248, 244, 251, 169  @ 4 A3
	voice_directsound 60, 0, DirectSoundWaveData_alto_sax_72, 248, 245, 252, 170  @ 5 C4
	voice_directsound 60, 0, DirectSoundWaveData_alto_sax_74, 248, 246, 253, 171  @ 6 D4
	voice_directsound 60, 0, DirectSoundWaveData_alto_sax_80, 248, 247, 254, 172  @ 7 G#4
	voice_directsound 60, 0, DirectSoundWaveData_alto_sax_85, 248, 248, 255, 173  @ 8 C#5

