	.align 2
voicegroup202:: @ Mario & Luigi: Bowser's Inside Story Harpsichord Samples
	voice_directsound 60, 0, DirectSoundWaveData_mlrpg3_harpsichord_49, 255, 247, 0, 196  @ C#2
	voice_directsound 60, 0, DirectSoundWaveData_mlrpg3_harpsichord_61, 255, 248, 0, 196  @ C#3
	voice_directsound 60, 0, DirectSoundWaveData_mlrpg3_harpsichord_79, 255, 247, 0, 196  @ G#4
	voice_directsound 60, 0, DirectSoundWaveData_mlrpg3_harpsichord_92, 255, 246, 0, 196  @ G#5

