gText_Birch_Welcome:: @ 82C897B
    .string "Well, you're finally here! it's\n"
    .string "about time! Let's get started!\p"
    .string "Welcome to the world of Pokémon!\p"
    .string "My name is Stephanie.\p"
    .string "But I'm usually called the Pokémon\n"
	.string "professor.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "Behold, this is a “Pokémon”.$"

gText_Birch_MainSpeech:: @ 82C8A1F
    .string "The world is full of beautiful \n"
    .string "creatures known as Pokémon.\p"
    .string "We humans live together with them,\n"
    .string "sometimes as caring companions, and\l"
    .string "other times as cooperative helpers.\p"
    .string "We might also team up \n"
    .string "and battle others like us!\p"
    .string "But despite all of that, there \n"
    .string "are many secrets to Pokémon.\p"
    .string "Who knows how much we can learn\n"
    .string "from all of the species that exist?\p"
    .string "My job as a professor is to research\n"
    .string "the Pokémon of the Phantos region. \l"
    .string "Pretty interesting, right?\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
    .string "And who might you be?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
    .string "Are you a boy?\n"
    .string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
    .string "I see.\n"
    .string "Now, what's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
    .string "So it's {PLAYER}{KUN}, right?$"

gText_Birch_YourePlayer:: @ 82C8C2A
    .string "Ah, I understand!\p"
    .string "You're {PLAYER}{KUN} who's currently\n"
    .string "asleep in your room in Kurosiba Town.\l"
    .string "You might want to wake up soon!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
    .string "So, are you ready?\p"
    .string "Your very own adventure is about\n"
    .string "to unfold.\p"
    .string "Be brave, and leap into the\n"
    .string "world of Pokémon where thrills,\l"
    .string "adventure, and friendships await!\p"
    .string "Well, I look forward to seeing you.\n"
    .string "You can find me in my Pokémon lab.$"
	